config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'
  post '/user_projects', to: 'user_projects#create'
  devise_for :users
  resources :projects
  
  resources :stages
  resources :instructions

  get '/users/:id', to: 'users#show', as: 'user'

end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  belongs_to :stage
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :stages
  has_many :users, through: :user_projects
  has_many :user_projects
  has_many :instructions, through: :stages

end

app/models/stage.rb
class Stage < ActiveRecord::Base
  belongs_to :project
  has_many :instructions
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, through: :user_projects
  has_many :user_projects
end

app/models/user_project.rb
class UserProject < ActiveRecord::Base
  
  belongs_to :project 
  belongs_to :user 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
 
  def show
    @instruction = Instruction.find(params[:id])
    @intructions = Instruction.all
    @stage = Stage.find(params[:id])
    @stages = Stage.all
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


  def show
    if current_user

      @project = Project.find(params[:id])
      @projects = Project.all
      @project_stage = Stage.where(project_id: @project.id)
      @project_stage_instructions = Instruction.where(stage_id: @project_stage.first.id)
      @instructions = @project.instructions

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @instructions }

      end

    else

      flash[:notice] = "Please Log In to Continue"
      redirect_to root_path

    end


  end

end

app/controllers/stages_controller.rb
class StagesController < ApplicationController

  def show
    @stage = Stage.find(params[:id])
    @stages = Stage.all
  end

end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController
  skip_before_filter :verify_authenticity_token 
  def create
    #create a user project object and save to the database
    @user_project = UserProject.create(user_id:current_user.id, project_id: params[:project_id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_project }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @projects = Project.all
  end

  # this is a GET
  def show
    @user = current_user
    @projects = current_user.projects  
  end

  # GET
  def new
    @user = User.new
    @projects = Project.all
  end

  # POST 
  def create
    User.create(user_params)
    redirect_to(users_path)
  end

    # GET
  def edit
    @user = User.find(params[:id])
    @projects = Project.all
  end

    # PUT
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to(user_path)
  end


   # DELETE
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to(users_path)
  end

  def delete_project
    user = User.find(params[:id])
    home.projects.delete(Projects.find(params[:id]))
  end
 
 
private
  def user_params
    params.require(:user).permit(:name, {plant_ids: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/Projects/show.html.erb
<nav id="show-page-navigation">
  <ul class="nav-list-show">
    <li class="show-page-nav-item"><%= link_to 'Go To My Projects', current_user  %></li>
    <li class="show-page-nav-item"><a href="">View All Stages of This Project</a></li> 
    <li class="show-page-nav-item"><a href="/">Choose Another Project</a></li> 
  </ul>
</nav>

<h1 class="project-title" data-project-id="<%=@project.id%>"><%= @project.name %> : <span class="stage"></span></h1>


<div id="projectOverview">
  <h1 class="modal-title"><%= @project.name %></h1>
  <h2 class="modal-level"> Difficulty Level: <%= @project.difficulty_level %> </h2>
  <img id="scarf-user-pic" src="<%= @project.modal_image %>">
  <button class="closeModal" data-id="<%= @project.id %>">Let's start!</button>
</div> 



<div class="navbar-header">
  <h1 class="instructions-title">Instructions</h1>
  
    <ol id="instructions-list"> 
    
        
    </ol>


  <button id="go-back" type="submit" class="missed-something" data-index="0"> Go Back </button>
  <button id="next-stage" type="submit" class="i-am-done" data-index="0">I'm Done!</button>
</div> 

<div id="stage-image">



</div>

<div id="howToVideo">
  
</div>

app/views/Users/index.html.erb
  <h1 id="main-title">WELCOME TO THE </h1>

<div class="home-container">

  <img id="main-interknit" src="/assets/interknit_title.png">

 <!--  <h3 id="tag-line">Where Everyone Can Learn to Knit</h3>

  <h4 id="projects-title">Available Projects</h4> -->



  <% @projects.each do | project | %>

  <div class="here-are-projects">
    <ul class="projects_list">
      <li class="project-list-item"><%= link_to((image_tag(project.image, height: '260')), project_path(project)) %></li>
    </ul>
  </div>  
  
  <% end %> 


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/Users/show.html.erb
<ul class="my-projects-nav">

  <li class="link-home"><a href="/">Choose Another Project</a></li>
  <li class="welcome-user"> Welcome, <%=@user.email%> !</li>
  
</ul>

<h2 class="my-projects-title">My Projects</h2>

<% @projects.each do |project| %>
  <h3><%= link_to(project.name, project_path(project)) %></h3>
<% end %>

<div id="projects-container"> 
  <ul id="current-projects">

  </ul>

<img class="finito" src="/assets/finito.png">

<img class="continue" src="/assets/continue.png">

<img class="do-next" src="/assets/do-next.png">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InterKnit</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.css">
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

</head>
<body>


<div class="application_container">
<% if user_signed_in? %>
 <li class ="logout">
 <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
 </li>
<% else %>
 <li class="login">
 <%= link_to('Login', new_user_session_path)  %>  
 </li>
<% end %>

<% if user_signed_in? %>
 <li class="edit-registration">
 <%= link_to('Edit Registration', edit_user_registration_path) %>
 </li>
<% else %>
 <li class="register">
 <%= link_to('Register', new_user_registration_path)  %>
 </li>
<% end %>

</div>

<% if user_signed_in? %>
 <li class="my-projects-link">You are logged in as: <%= current_user.email%>
 <%= link_to 'View My Projects', current_user  %> 
 </li>
<% end %>


<%= yield %>

</body>
</html>